(function(){
  "use strict";
  const cfg=window.EW_CONFIG;
  const api=window.EW_AUTHORITY;
  const root=document.getElementById("sentenceRoot");
  const loading=document.getElementById("sentenceLoading");
  const loadingText=document.getElementById("sentenceLoadingText");

  const TASKS=Object.freeze([
    {id:"sc01",kind:"Fill the Gap",visual:"💧",prompt:"Students should ___ enough water during hot weather.",tokens:["drink","repair","borrow","paint"],answer:["drink"],hint:"ใช้คำกริยาที่เข้าคู่กับ water"},
    {id:"sc02",kind:"Word Order",visual:"🔒",prompt:"เรียงบล็อกให้เป็นประโยคที่ถูกต้อง",tokens:["your password","Please","private","keep"],answer:["Please","keep","your password","private"],hint:"ประโยคคำสั่งขึ้นต้นด้วย Please"},
    {id:"sc03",kind:"Repair",visual:"♻️",prompt:"ซ่อมประโยค: We should reducing plastic waste.",tokens:["We","should","reduce","plastic waste"],answer:["We","should","reduce","plastic waste"],hint:"หลัง should ใช้กริยารูปพื้นฐาน"},
    {id:"sc04",kind:"Word Order",visual:"🏛️",prompt:"เรียงประโยคเกี่ยวกับการเริ่มทัวร์",tokens:["at 10 a.m.","the museum tour","will begin","The guide"],answer:["The guide","will begin","the museum tour","at 10 a.m."],hint:"เริ่มด้วยประธาน The guide"},
    {id:"sc05",kind:"Fill the Gap",visual:"📝",prompt:"You need to ___ the application form before Friday.",tokens:["submit","climb","mix","throw"],answer:["submit"],hint:"คำนี้หมายถึงส่งแบบฟอร์มอย่างเป็นทางการ"},
    {id:"sc06",kind:"Repair",visual:"📚",prompt:"ซ่อมประโยค: This app helps students practicing vocabulary.",tokens:["This app","helps students","practice","new vocabulary"],answer:["This app","helps students","practice","new vocabulary"],hint:"หลัง helps someone ใช้กริยารูปพื้นฐานได้"},
    {id:"sc07",kind:"Word Order",visual:"💡",prompt:"เรียงประโยคเกี่ยวกับการแบ่งปันความคิด",tokens:["before choosing","Our team","ideas","will share","the best one"],answer:["Our team","will share","ideas","before choosing","the best one"],hint:"Our team เป็นประธานของประโยค"},
    {id:"sc08",kind:"Fill the Gap",visual:"🚸",prompt:"Always ___ both sides before crossing the road.",tokens:["check","cook","collect","design"],answer:["check"],hint:"คำแนะนำด้านความปลอดภัยก่อนข้ามถนน"},
    {id:"sc09",kind:"Repair",visual:"🏆",prompt:"ซ่อมประโยค: The school will organized an English competition.",tokens:["The school","will organize","an English competition","next week"],answer:["The school","will organize","an English competition","next week"],hint:"หลัง will ใช้กริยารูปพื้นฐาน"},
    {id:"sc10",kind:"Word Order",visual:"💬",prompt:"เรียงคำถามให้ถูกต้อง",tokens:["this word","Can you","in a sentence","use"],answer:["Can you","use","this word","in a sentence"],hint:"คำถามขึ้นต้นด้วย Can you"}
  ]);

  const state={identity:null,authority:null,tasks:[],index:0,built:[],attempts:[],firstTryCorrect:0,hintsUsed:0,points:0,startedAt:0,pending:null};
  const h=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  function shuffle(a){const x=a.slice();for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
  function readIdentity(){try{return JSON.parse(localStorage.getItem(cfg.cacheKeys.identity)||"null");}catch(_){return null;}}
  function showLoading(m){loadingText.textContent=m||"กำลังโหลดข้อมูล…";loading.hidden=false;}function hideLoading(){loading.hidden=true;}
  function goPassport(){location.href="./index.html?resume=sentence&v=20260803-sentence1";}
  function shell(content){return `<div class="shell"><header class="top"><button id="backBtn" class="icon-btn">←</button><div class="title"><strong>🏙️ Sentence City</strong><small>Build & Repair Mission</small></div><button id="exitBtn" class="icon-btn">🗺️</button></header>${content}</div>`;}
  function wireBack(){["backBtn","exitBtn"].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener("click",goPassport);});}
  function friendly(code){const m={REQUEST_TIMEOUT:"Server ตอบกลับช้าเกินกำหนด",NETWORK_ERROR:"เครือข่ายขัดข้อง",PLAYER_NOT_FOUND:"ไม่พบรหัสผู้เล่น",PLAYER_INACTIVE:"รหัสผู้เล่นถูกระงับ",STAGE_LOCKED:"ด่านนี้ยังไม่ปลดล็อก",RECEIPT_MISSING:"ไม่ได้รับหลักฐานยืนยันจาก Server",RESUME_FAILED:"กู้คืนความก้าวหน้าไม่สำเร็จ"};return m[code]||code||"เกิดข้อผิดพลาด";}

  function renderNeedLogin(){root.innerHTML=shell(`<section class="intro"><div class="hero">🔐</div><h1>กรุณาเข้าสู่ระบบก่อน</h1><p class="lead">ต้องเข้าสู่ English Week Passport ก่อนเข้า Sentence City</p><div class="actions"><button id="loginBtn" class="btn primary">กลับหน้า Login</button></div></section>`);wireBack();document.getElementById("loginBtn").onclick=goPassport;}
  function renderLocked(){root.innerHTML=shell(`<section class="intro"><div class="hero">🔒</div><h1>ด่านนี้ยังไม่ปลดล็อก</h1><p class="lead">ต้องผ่าน Category Forest ก่อน</p><div class="actions"><button id="lockedBtn" class="btn primary">กลับ Passport</button></div></section>`);wireBack();document.getElementById("lockedBtn").onclick=goPassport;}
  function renderIntro(msg){root.innerHTML=shell(`<section class="intro"><div class="hero">🏙️</div><h1>Sentence City</h1><p class="lead">สร้าง เรียง และซ่อมประโยคด้วยบล็อกคำ 10 ภารกิจ ใช้การแตะเป็นหลักและลากวางได้บนอุปกรณ์ที่รองรับ</p>${msg?`<div class="notice">${h(msg)}</div>`:""}<div class="notice"><strong>เกณฑ์ผ่าน 70%:</strong> ต้องตอบถูกตั้งแต่การตรวจครั้งแรกอย่างน้อย 7 ภารกิจ แต่ยังแก้ไขต่อจนจบได้ทุกข้อ</div><div class="actions"><button id="startBtn" class="btn primary">เข้าเมืองและเริ่มสร้างประโยค</button><button id="introBack" class="btn secondary">กลับ Passport</button></div></section>`);wireBack();document.getElementById("startBtn").onclick=startGame;document.getElementById("introBack").onclick=goPassport;}

  function startGame(){state.tasks=shuffle(TASKS);state.index=0;state.built=[];state.attempts=TASKS.map(()=>0);state.firstTryCorrect=0;state.hintsUsed=0;state.points=0;state.startedAt=Date.now();state.pending=null;renderTask();}
  function renderTask(){const t=state.tasks[state.index];if(!t)return finish();state.built=[];const bank=shuffle(t.tokens.map((label,i)=>({id:`${t.id}-${i}`,label})));root.innerHTML=shell(`<section class="hud"><div class="hud-box"><small>ภารกิจ</small><strong>${state.index+1} / ${state.tasks.length}</strong><div class="progress"><span style="width:${Math.round(state.index/state.tasks.length*100)}%"></span></div></div><div class="hud-box"><small>Mastery</small><strong>${state.firstTryCorrect}</strong></div><div class="hud-box"><small>คะแนน</small><strong>${state.points}</strong></div></section><section class="card game-card"><span class="round-chip">${h(t.kind)}</span><div class="prompt"><span class="visual">${t.visual}</span><h2>${h(t.prompt)}</h2></div><div id="buildZone" class="build-zone empty" tabindex="0"></div><div id="tokenBank" class="token-bank">${bank.map(x=>`<button class="token" type="button" draggable="true" data-token-id="${h(x.id)}" data-label="${h(x.label)}">${h(x.label)}</button>`).join("")}</div><div id="feedback" class="feedback">แตะบล็อกคำตามลำดับ หรือกดค้างแล้วลากเข้าพื้นที่สร้างประโยค</div><div class="check-row"><button id="checkBtn" class="btn primary">ตรวจประโยค</button><button id="hintBtn" class="hint">คำใบ้</button></div></section>`);wireBack();wireTokens();}
  function wireTokens(){document.querySelectorAll(".token").forEach(btn=>{btn.addEventListener("click",()=>addToken(btn.dataset.tokenId,btn.dataset.label));btn.addEventListener("dragstart",e=>{e.dataTransfer.setData("text/token-id",btn.dataset.tokenId);e.dataTransfer.setData("text/token-label",btn.dataset.label);});});const zone=document.getElementById("buildZone");zone.addEventListener("dragover",e=>e.preventDefault());zone.addEventListener("drop",e=>{e.preventDefault();addToken(e.dataTransfer.getData("text/token-id"),e.dataTransfer.getData("text/token-label"));});document.getElementById("checkBtn").onclick=checkAnswer;document.getElementById("hintBtn").onclick=showHint;}
  function addToken(id,label){if(state.built.some(x=>x.id===id))return;state.built.push({id,label});const btn=document.querySelector(`[data-token-id="${CSS.escape(id)}"]`);if(btn){btn.disabled=true;btn.classList.add("used");}renderBuilt();}
  function removeToken(id){state.built=state.built.filter(x=>x.id!==id);const btn=document.querySelector(`[data-token-id="${CSS.escape(id)}"]`);if(btn){btn.disabled=false;btn.classList.remove("used");}renderBuilt();}
  function renderBuilt(){const zone=document.getElementById("buildZone");zone.classList.toggle("empty",state.built.length===0);zone.innerHTML=state.built.map(x=>`<span class="built-token">${h(x.label)}<button type="button" data-remove="${h(x.id)}">×</button></span>`).join("");zone.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>removeToken(b.dataset.remove));}
  function normalize(parts){return parts.join(" ").replace(/[?.!,]/g,"").replace(/\s+/g," ").trim().toLowerCase();}
  function setFeedback(msg,cls){const el=document.getElementById("feedback");el.className=`feedback${cls?` ${cls}`:""}`;el.innerHTML=msg;}
  function checkAnswer(){const t=state.tasks[state.index];state.attempts[state.index]+=1;const ok=normalize(state.built.map(x=>x.label))===normalize(t.answer);if(ok){if(state.attempts[state.index]===1){state.firstTryCorrect+=1;state.points+=150;}else state.points+=80;setFeedback("<strong>ประโยคถูกต้อง! เมืองส่วนนี้เปิดแล้ว ✨</strong>","good");document.querySelectorAll(".token,#checkBtn,#hintBtn,.built-token button").forEach(x=>x.disabled=true);setTimeout(()=>{state.index+=1;renderTask();},850);}else{setFeedback("<strong>ลำดับหรือคำยังไม่ถูกต้อง</strong><br>แตะ × เพื่อนำบล็อกออก แล้วลองจัดใหม่","bad");}}
  function showHint(){const t=state.tasks[state.index];state.hintsUsed+=1;setFeedback(`<strong>คำใบ้:</strong> ${h(t.hint)}`,"");document.getElementById("hintBtn").disabled=true;}
  function payload(){const durationMs=Date.now()-state.startedAt;return{playerId:state.identity.playerId,nickname:state.authority?.profile?.nickname||state.authority?.profile?.fullName||state.identity.nickname,stageId:"sentence_city",score:state.firstTryCorrect,total:state.tasks.length,durationMs,clientPoints:state.points,inputMode:"touch-drag-builder",answers:state.tasks.map((t,i)=>({itemId:t.id,selected:"sentence-built",correctAnswer:t.answer.join(" "),correct:state.attempts[i]===1,attempts:state.attempts[i],inputMode:"touch-drag-builder"})),gameMetrics:{firstTryCorrect:state.firstTryCorrect,hintsUsed:state.hintsUsed,totalAttempts:state.attempts.reduce((a,b)=>a+b,0)}};}
  async function finish(){state.pending=payload();showLoading("กำลังบันทึกผล Sentence City…");try{const r=await api.submitGame(state.pending);if(!r?.ok||!r.authority)throw new Error(r?.error||"RECEIPT_MISSING");state.authority=r.authority;renderResult(r);}catch(e){renderSubmitError(e);}finally{hideLoading();}}
  function renderResult(r){const p=state.pending;const accuracy=Math.round(p.score/p.total*100);const passed=Boolean(r.passed);const sec=Math.floor(p.durationMs/1000);root.innerHTML=shell(`<section class="result"><div class="hero">${passed?"🌟":"💪"}</div><h1>${passed?"ผ่าน Sentence City!":"ยังไม่ผ่านภารกิจ"}</h1><p class="lead">${passed?"Server ยืนยันผลและปลดล็อกด่านถัดไปแล้ว":`ต้องตอบถูกในการตรวจครั้งแรกอย่างน้อย ${Math.ceil((r.passMark||70)/10)} ข้อ`}</p><div class="result-ring" style="--angle:${accuracy*3.6}deg"><div><strong>${accuracy}%</strong><small>Mastery</small></div></div><div class="metrics"><div class="metric"><strong>${state.firstTryCorrect}/10</strong><small>First try</small></div><div class="metric"><strong>${state.hintsUsed}</strong><small>คำใบ้</small></div><div class="metric"><strong>${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}</strong><small>เวลา</small></div></div><div class="notice ok">Receipt: ${h(r.receiptId||"SERVER-OK")} • Touch/Drag</div><div class="actions ${passed?"":"two"}">${passed?"":'<button id="retryBtn" class="btn secondary">เล่นอีกครั้ง</button>'}<button id="resultBack" class="btn primary">กลับ Passport</button></div></section>`);wireBack();if(!passed)document.getElementById("retryBtn").onclick=startGame;document.getElementById("resultBack").onclick=goPassport;}
  function renderSubmitError(e){root.innerHTML=shell(`<section class="result"><div class="hero">📡</div><h1>ยังยืนยันผลไม่ได้</h1><p class="lead">จะไม่ปลดล็อกด่านถัดไปจนกว่า Server จะออก Receipt</p><div class="notice error">${h(friendly(e?.message))}</div><div class="actions"><button id="retrySubmit" class="btn primary">ส่งผลอีกครั้ง</button><button id="submitBack" class="btn secondary">กลับ Passport</button></div></section>`);wireBack();document.getElementById("retrySubmit").onclick=async()=>{showLoading("กำลังส่งผลอีกครั้ง…");try{const r=await api.submitGame(state.pending);if(!r?.ok||!r.authority)throw new Error(r?.error||"RECEIPT_MISSING");renderResult(r);}catch(err){renderSubmitError(err);}finally{hideLoading();}};document.getElementById("submitBack").onclick=goPassport;}
  function renderLoadError(e){root.innerHTML=shell(`<section class="result"><div class="hero">⚠️</div><h1>โหลดสถานะไม่สำเร็จ</h1><div class="notice error">${h(friendly(e?.message))}</div><div class="actions"><button id="reload" class="btn primary">ลองใหม่</button><button id="loadBack" class="btn secondary">กลับ Passport</button></div></section>`);wireBack();document.getElementById("reload").onclick=initialize;document.getElementById("loadBack").onclick=goPassport;}
  async function initialize(){state.identity=readIdentity();if(!state.identity?.playerId)return renderNeedLogin();showLoading("กำลังตรวจสถานะ Sentence City…");try{state.authority=await api.resume(state.identity.playerId,state.identity.nickname);if(!state.authority?.ok)throw new Error(state.authority?.error||"RESUME_FAILED");if(!state.authority.progress?.unlocked?.includes("sentence_city"))return renderLocked();renderIntro();}catch(e){renderLoadError(e);}finally{hideLoading();}}
  initialize();
}());
