# === /tools/ml/train_goodjunk.py ===
# Train 2-task logistic models from ML recorder JSONL
# Outputs: /herohealth/vr/goodjunk-model.js
# FULL v20260301-TRAIN-EXPORT
import os, json, argparse
import numpy as np

def load_jsonl(path):
  rows = []
  with open(path, "r", encoding="utf-8") as f:
    for line in f:
      line = line.strip()
      if not line: 
        continue
      obj = json.loads(line)
      if obj.get("type") == "frame":
        rows.append(obj)
  return rows

FEATURE_ORDER = [
  "miss","dMiss","accPct","accRecent","combo","feverPct","shield",
  "missGoodExpired","missJunkHit","medianRtGoodMs"
]

def to_xy(rows):
  X = []
  y1 = []  # hazardRisk_1s
  y3 = []  # miss_3s
  for r in rows:
    x = r.get("x", {})
    y = r.get("y", {})
    if y.get("hazardRisk_1s") is None or y.get("miss_3s") is None:
      continue
    vec = []
    for k in FEATURE_ORDER:
      v = x.get(k, 0.0)
      if v is None: v = 0.0
      vec.append(float(v))
    X.append(vec)
    y1.append(int(y["hazardRisk_1s"]))
    y3.append(int(y["miss_3s"]))
  return np.asarray(X, dtype=np.float32), np.asarray(y1, dtype=np.int64), np.asarray(y3, dtype=np.int64)

def standardize_fit(X):
  mu = X.mean(axis=0)
  sd = X.std(axis=0) + 1e-6
  return mu, sd

def standardize_apply(X, mu, sd):
  return (X - mu) / sd

def train_logreg(X, y, lr=0.08, steps=1200, l2=0.02):
  # simple logistic regression (GD) to avoid dependency
  n, d = X.shape
  w = np.zeros((d,), dtype=np.float32)
  b = 0.0
  for t in range(steps):
    z = X @ w + b
    p = 1.0 / (1.0 + np.exp(-z))
    # gradients
    grad_w = (X.T @ (p - y)) / n + l2 * w
    grad_b = float((p - y).mean())
    w -= lr * grad_w
    b -= lr * grad_b
  return float(b), w.astype(np.float32)

def auc_like(y, p):
  # quick proxy: accuracy at 0.5 + balanced accuracy (no heavy deps)
  y = y.astype(np.int64)
  pred = (p >= 0.5).astype(np.int64)
  acc = float((pred == y).mean())
  # balanced
  pos = (y == 1)
  neg = (y == 0)
  tpr = float((pred[pos] == 1).mean()) if pos.any() else 0.0
  tnr = float((pred[neg] == 0).mean()) if neg.any() else 0.0
  bal = 0.5 * (tpr + tnr)
  return acc, bal

def export_js(out_path, mu, sd, b1, w1, b3, w3):
  js = f"""// === /herohealth/vr/goodjunk-model.js ===
// Exported model for GoodJunk predictions
// Generated by tools/ml/train_goodjunk.py
// FULL v20260301-MODEL-EXPORT
'use strict';

function sigmoid(z){{ return 1 / (1 + Math.exp(-z)); }}
function dot(w, x){{ let s=0; for(let i=0;i<w.length;i++) s += (w[i]||0) * (x[i]||0); return s; }}

export const MODEL_META = {{
  version: 'logreg-export-v20260301',
  featureOrder: {json.dumps(FEATURE_ORDER, ensure_ascii=False)}
}};

// Standardization params
export const STD = {{
  mu: {json.dumps(mu.tolist())},
  sd: {json.dumps(sd.tolist())}
}};

// Weights
export const WEIGHTS = {{
  hazardRisk_1s: {{ b: {b1:.8f}, w: {json.dumps([float(x) for x in w1.tolist()])} }},
  miss_3s:       {{ b: {b3:.8f}, w: {json.dumps([float(x) for x in w3.tolist()])} }}
}};

export function predictProba(xVecRaw){{
  try{{
    const x = xVecRaw.map((v,i)=> (Number(v||0) - STD.mu[i]) / (STD.sd[i]||1e-6));
    const h = sigmoid(WEIGHTS.hazardRisk_1s.b + dot(WEIGHTS.hazardRisk_1s.w, x));
    const m = sigmoid(WEIGHTS.miss_3s.b       + dot(WEIGHTS.miss_3s.w, x));
    return {{ hazardRisk: h, miss3s: m }};
  }}catch(e){{
    return {{ hazardRisk: 0.15, miss3s: 0.08 }};
  }}
}}
"""
  os.makedirs(os.path.dirname(out_path), exist_ok=True)
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(js)

def main():
  ap = argparse.ArgumentParser()
  ap.add_argument("--jsonl", required=True, help="path to mlrec_*.jsonl")
  ap.add_argument("--out", default="herohealth/vr/goodjunk-model.js", help="export JS path (repo-relative)")
  ap.add_argument("--steps", type=int, default=1400)
  ap.add_argument("--lr", type=float, default=0.08)
  ap.add_argument("--l2", type=float, default=0.02)
  args = ap.parse_args()

  rows = load_jsonl(args.jsonl)
  if not rows:
    raise SystemExit("No frame rows found in JSONL.")

  X, y1, y3 = to_xy(rows)
  if len(X) < 200:
    raise SystemExit(f"Too few samples: {len(X)} (need ~200+)")

  # Standardize
  mu, sd = standardize_fit(X)
  Xs = standardize_apply(X, mu, sd)

  # Train both heads
  b1, w1 = train_logreg(Xs, y1, lr=args.lr, steps=args.steps, l2=args.l2)
  b3, w3 = train_logreg(Xs, y3, lr=args.lr, steps=args.steps, l2=args.l2)

  # Quick eval
  p1 = 1/(1+np.exp(-(Xs @ w1 + b1)))
  p3 = 1/(1+np.exp(-(Xs @ w3 + b3)))
  acc1, bal1 = auc_like(y1, p1)
  acc3, bal3 = auc_like(y3, p3)
  print(f"[hazardRisk_1s] acc={acc1:.3f} bal={bal1:.3f} posRate={y1.mean():.3f}")
  print(f"[miss_3s]      acc={acc3:.3f} bal={bal3:.3f} posRate={y3.mean():.3f}")

  # Export
  export_js(args.out, mu, sd, b1, w1, b3, w3)
  print("Exported:", args.out)

if __name__ == "__main__":
  main()
