(function(){
 const $=s=>document.querySelector(s), stage=$('#gameStage'); let state={phase:0,score:0,stability:100,combo:0,found:[],classes:{},fixes:{},explain:null}; let current;
 const choose=arr=>arr[Math.floor(Math.random()*arr.length)];
 function start(){current=choose(W1_CASES); state={phase:0,score:0,stability:100,combo:0,found:[],classes:{},fixes:{},explain:null}; updateHud(); render();}
 function updateHud(){ $('#stabilityValue').textContent=state.stability; $('#comboValue').textContent=state.combo; $('#scoreValue').textContent=state.score; }
 function markPhase(){ document.querySelectorAll('.phase').forEach((e,i)=>{e.classList.toggle('active',i===state.phase); e.disabled=i>state.phase;}); }
 function add(points,good=true){if(good){state.combo++;state.score+=points+Math.min(state.combo,8);state.stability=Math.min(100,state.stability+2);}else{state.combo=0;state.stability=Math.max(0,state.stability-10);}updateHud();}
 function next(){state.phase++;markPhase();render();window.scrollTo({top:0,behavior:'smooth'});}
 function render(){markPhase(); const fn=[observe,diagnose,fix,userTest,explain][state.phase];fn&&fn();}
 function observe(){stage.innerHTML=`<section class="stage-card"><div class="stage-grid"><div><p class="eyebrow">USER SIGNAL</p><blockquote class="case-quote">${current.quote}</blockquote><div class="case-meta"><span>บริการ: ${current.service}</span><span>บริบท: ${current.device}</span><span>เป้าหมาย: ส่งคำร้องให้สำเร็จ</span></div><p class="muted">แตะบนหน้าจอจำลองเพื่อค้นหาจุดที่ทำให้ผู้ใช้ติดขัด มีทั้งหมด <b>${current.issues.length}</b> จุด</p><div class="mock-screen" aria-label="หน้าจอจำลองมีปัญหา"><div class="mock-top"><b>Smart Campus</b><div class="mock-nav"><span>บริการ</span><span>ช่วยเหลือ</span><span>บัญชี</span></div></div><div class="mock-content"><h3>ส่งคำร้องขอความช่วยเหลือ</h3><p>กรุณากรอกข้อมูลของคุณให้ครบเพื่อดำเนินการตามขั้นตอนภายในระบบศูนย์กลางบริการนักศึกษา</p><div class="mock-form"><span class="mock-label">เรื่องที่ต้องการติดต่อ</span><div class="mock-input">เลือกหัวข้อบริการ</div><span class="mock-label" style="margin-top:8px">รายละเอียดเพิ่มเติม</span><div class="mock-input mock-textarea">พิมพ์ข้อความ...</div><div class="mock-btn-row"><button class="mock-send" type="button">ดำเนินการส่ง</button></div><div class="mock-no-feedback"></div></div><div class="mock-side-menu"><span>บริการทั่วไป</span><span>บริการนักศึกษา</span><span>ช่วยเหลือนักศึกษา</span><span>คำร้องนักศึกษา</span><span>บริการอื่น ๆ</span></div></div><button class="hotspot hs-menu" data-id="menu" aria-label="พื้นที่เมนู"></button><button class="hotspot hs-font" data-id="font" aria-label="พื้นที่ข้อความ"></button><button class="hotspot hs-cta" data-id="cta" aria-label="พื้นที่ปุ่มส่ง"></button><button class="hotspot hs-feedback" data-id="feedback" aria-label="พื้นที่ feedback"></button><button class="hotspot hs-mobile" data-id="mobile" aria-label="พื้นที่ touch target"></button></div></div><aside class="scan-side"><p class="eyebrow">FRICTION HUNT</p><h2>ค้นหาจุดพังของประสบการณ์ผู้ใช้</h2><p>อย่าคลิกสุ่ม: มองจากเป้าหมายของผู้ใช้ก่อนว่าเขาต้องการทำอะไรให้สำเร็จ และอะไรทำให้เขาสับสน</p><div class="issue-counter">พบแล้ว <b id="foundCount">0</b> / ${current.issues.length} จุด</div><div id="foundList" class="found-list"><div class="found-item"><strong>ยังไม่พบสัญญาณ</strong><small>ลองดูเมนู ข้อความ ปุ่ม และสิ่งที่เกิดขึ้นหลังการส่งข้อมูล</small></div></div><div class="notification warning">Critical Alert: ต้องค้นหาและแก้ปัญหาสำคัญให้ครบ จึงจะผ่าน Mission ได้</div><div class="stage-actions"><button id="scanNext" class="primary-btn" type="button" disabled>วิเคราะห์ต่อ →</button></div></aside></div></section>`;
  document.querySelectorAll('.hotspot').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.id; if(state.found.includes(id))return;state.found.push(id);el.classList.add('found');const issue=current.issues.find(x=>x.id===id);add(7,true);$('#foundCount').textContent=state.found.length;const list=$('#foundList');if(state.found.length===1)list.innerHTML='';list.insertAdjacentHTML('beforeend',`<div class="found-item"><strong>${issue.name}</strong><small>${issue.detail}</small></div>`);if(state.found.length===current.issues.length){$('#scanNext').disabled=false;$('#scanNext').textContent='จัดประเภทปัญหา →';}}));
  $('#scanNext').addEventListener('click',next);
 }
 function diagnose(){stage.innerHTML=`<section class="stage-card"><p class="eyebrow">DIAGNOSE</p><h2>ปัญหานี้กระทบผู้ใช้ในมิติใดมากที่สุด?</h2><p class="muted">เลือกคำตอบที่ “ชัดที่สุด” สำหรับแต่ละจุด แม้บางปัญหาจะกระทบได้มากกว่าหนึ่งมิติ</p><div class="classification-grid">${current.issues.map(issue=>`<article class="issue-classify" data-id="${issue.id}"><h3>${issue.name}${issue.critical?' <span style="color:var(--red);font-size:.72rem">● CRITICAL</span>':''}</h3><p>${issue.detail}</p><div class="button-row">${['Usability','Emotion','Accessibility','Value'].map(cat=>`<button class="chip-btn" type="button" data-cat="${cat}">${cat}</button>`).join('')}</div></article>`).join('')}</div><div class="stage-actions"><button id="diagNext" class="primary-btn" type="button" disabled>เลือกวิธีแก้ →</button></div></section>`;
  document.querySelectorAll('.issue-classify').forEach(card=>card.querySelectorAll('.chip-btn').forEach(btn=>btn.addEventListener('click',()=>{card.querySelectorAll('.chip-btn').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');state.classes[card.dataset.id]=btn.dataset.cat; const all=Object.keys(state.classes).length===current.issues.length;$('#diagNext').disabled=!all;})));
  $('#diagNext').addEventListener('click',()=>{current.issues.forEach(issue=>add(4,state.classes[issue.id]===issue.cat));next();});
 }
 function fix(){stage.innerHTML=`<section class="stage-card"><p class="eyebrow">DESIGN FIX</p><h2>เลือกวิธีแก้ที่ช่วยผู้ใช้ได้จริง</h2><p class="muted">ให้ความสำคัญกับปัญหา Critical ก่อน: งานต้องทำสำเร็จ อ่านได้ และรู้สถานะของระบบ</p><div class="fix-grid">${current.issues.map(issue=>`<article class="fix-card" data-id="${issue.id}"><h3>${issue.name}</h3>${W1_FIXES[issue.fix].map((f,i)=>`<button type="button" class="choice-btn" data-index="${i}">${String.fromCharCode(65+i)}. ${f.t}</button>`).join('')}</article>`).join('')}</div><div class="stage-actions"><button id="fixNext" class="primary-btn" type="button" disabled>ดูผล User Simulation →</button></div></section>`;
  document.querySelectorAll('.fix-card').forEach(card=>card.querySelectorAll('.choice-btn').forEach(btn=>btn.addEventListener('click',()=>{card.querySelectorAll('.choice-btn').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');state.fixes[card.dataset.id]=Number(btn.dataset.index);$('#fixNext').disabled=Object.keys(state.fixes).length!==current.issues.length;})));
  $('#fixNext').addEventListener('click',()=>{current.issues.forEach(issue=>{const ok=W1_FIXES[issue.fix][state.fixes[issue.id]].ok;add(8,ok);});next();});
 }
 function userTest(){const fixCorrect=current.issues.filter(i=>W1_FIXES[i.fix][state.fixes[i.id]].ok).length;const criticalFixed=current.issues.filter(i=>i.critical).every(i=>W1_FIXES[i.fix][state.fixes[i.id]].ok);const foundPct=state.found.length/current.issues.length;const success=Math.round(42+fixCorrect/current.issues.length*52);const errors=Math.max(0,7-fixCorrect);const time=Math.max(38,125-fixCorrect*16);state.sim={fixCorrect,criticalFixed,foundPct,success,errors,time};stage.innerHTML=`<section class="stage-card"><p class="eyebrow">USER TEST SIMULATION</p><h2>${criticalFixed?'ผู้ใช้เริ่มทำงานสำเร็จแล้ว':'ระบบยังมี Critical Friction เหลืออยู่'}</h2><p class="muted">ผลจำลองนี้สะท้อนผลของการตัดสินใจออกแบบ ไม่ใช่แค่จำนวนคำตอบที่ถูก</p><div class="simulation-result"><article class="metric-card"><span>Task Success</span><b class="${success>=70?'metric-good':'metric-bad'}">${success}%</b></article><article class="metric-card"><span>Misclicks</span><b class="${errors<=2?'metric-good':'metric-bad'}">${errors}</b></article><article class="metric-card"><span>Time on Task</span><b class="${time<=70?'metric-good':'metric-bad'}">${time}s</b></article><article class="metric-card"><span>Critical Gate</span><b class="${criticalFixed?'metric-good':'metric-bad'}">${criticalFixed?'PASS':'FAIL'}</b></article></div><div class="timeline"><div class="timeline-item">ผู้ใช้มองหาเมนูและเริ่มกรอกแบบฟอร์ม</div><div class="timeline-item">${fixCorrect>=3?'CTA และข้อมูลสำคัญทำให้ผู้ใช้เข้าใจสิ่งที่ต้องทำต่อ':'ผู้ใช้ยังเสียเวลาเพราะ CTA หรือข้อมูลสำคัญไม่ชัด'}</div><div class="timeline-item">${criticalFixed?'ผู้ใช้ได้รับสถานะยืนยัน จึงไม่ต้องส่งซ้ำ':'ผู้ใช้ยังไม่แน่ใจว่าส่งสำเร็จหรือไม่ และอาจทำรายการซ้ำ'}</div></div><div class="stage-actions"><button id="testNext" class="primary-btn" type="button">Explain Check →</button></div></section>`;$('#testNext').addEventListener('click',next);}
 function explain(){const good='การเพิ่มข้อความยืนยันและสถานะที่ตรวจสอบได้ช่วยลดความกังวล ทำให้ผู้ใช้รู้ว่าระบบรับข้อมูลแล้วและไม่ต้องส่งซ้ำ';const opts=[good,'เพราะทำให้หน้าจอดูมีสีสันขึ้น จึงน่าจะทำให้ผู้ใช้ชอบระบบมากกว่าเดิม','เพราะระบบควรซ่อนผลลัพธ์ไว้เพื่อให้ผู้ใช้กลับมาเปิดหน้าเดิมหลายครั้ง','เพราะปุ่มยืนยันควรอยู่ห่างจากฟอร์ม เพื่อให้ผู้ใช้มีเวลาคิดนานขึ้น'];stage.innerHTML=`<section class="stage-card explain-card"><p class="eyebrow">EXPLAIN CHECK</p><h2>เหตุใดการเพิ่มข้อความยืนยันหลังส่งคำร้องจึงช่วย UX?</h2><p>เลือกคำอธิบายที่เชื่อม “การออกแบบ” กับ “ผลที่เกิดกับผู้ใช้” ได้ดีที่สุด</p><div class="explain-options">${opts.map((o,i)=>`<button class="explain-option" type="button" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div></section>`;document.querySelectorAll('.explain-option').forEach(btn=>btn.addEventListener('click',()=>{state.explain=Number(btn.dataset.i);add(12,state.explain===0);summary();}));}
 function summary(){const c=state.sim; const raw=Math.min(100,Math.round((state.score/(current.issues.length*19+12))*100)); const score=Math.max(0,raw); let stars=0;if(score>=60 && c.criticalFixed && state.explain===0)stars=1;if(score>=75&&c.fixCorrect>=4)stars=2;if(score>=90&&c.fixCorrect===current.issues.length&&state.stability>=80)stars=3;const skills={empathy:Math.round((state.classes?Object.keys(state.classes).filter(id=>state.classes[id]===current.issues.find(i=>i.id===id).cat).length/current.issues.length:0)*35),clarity:Math.round(c.fixCorrect/current.issues.length*40),flow:Math.round(c.criticalFixed?25:10)};const dxp=stars?Math.round(45+stars*25+score/4):0;UXQ.addMissionResult('w1',{score,stars,dxp,skills,caseId:current.id,completedAt:new Date().toISOString()});const title=stars?['','Mission Clear!','Mastery Achieved!','Expert Rescue!'][stars]:'Recovery Needed';const note=stars?'คุณผ่าน W1 แล้ว W2 จะพร้อมเมื่อ Mission Pack ถัดไปถูกเพิ่มเข้าระบบ':'ยังผ่านไม่ครบ: ลองเล่นใหม่โดยโฟกัส Critical Error และเหตุผลของการออกแบบ';stage.innerHTML=`<section class="stage-card summary-hero"><p class="eyebrow">MISSION REPORT</p><div class="star-result">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><h2>${title}</h2><div class="score-big">${score}</div><p class="muted">คะแนน Mission • ${current.title}</p><div class="summary-grid"><article><span>DXP ได้รับ</span><b>+${dxp}</b></article><article><span>Critical Gate</span><b class="${c.criticalFixed?'metric-good':'metric-bad'}">${c.criticalFixed?'PASS':'FAIL'}</b></article><article><span>Best Fixes</span><b>${c.fixCorrect}/${current.issues.length}</b></article></div><p class="summary-note">${note}</p><div class="stage-actions" style="justify-content:center"><a class="ghost-btn" href="./index.html">กลับ Mission Map</a><button id="replayBtn" class="primary-btn" type="button">เล่นซ้ำ • Case ใหม่</button></div></section>`;$('#replayBtn').addEventListener('click',start);}
 $('#howBtn').addEventListener('click',()=>$('#howDialog').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.close).close()));start();
})();
