(function(){
  const root=document.getElementById('root'), hud=document.getElementById('hud'), skyEl=document.getElementById('sky');
  const btnStart=document.getElementById('btnStart'), btnPause=document.getElementById('btnPause'), btnResume=document.getElementById('btnResume'), btnReset=document.getElementById('btnReset'), statusEl=document.getElementById('status');
  let paused=false,pauseAt=0,pauseAccum=0;
  function pauseGame(){ if(paused) return; paused=true; pauseAt=performance.now()/1000; }
  function resumeGame(){ if(!paused) return; const now=performance.now()/1000; pauseAccum+=now-pauseAt; paused=false; }
  function showFirstTimeOverlay(key,msg){ if(localStorage.getItem(key)) return; const d=document.createElement('div'); d.style.cssText='position:fixed;inset:0;background:rgba(5,10,20,.72);z-index:9999;display:flex;align-items:center;justify-content:center;color:#e2e8f0;font:16px system-ui;text-align:center';
    d.innerHTML='<div style="max-width:620px;background:#0f172a;border:1px solid #334155;border-radius:14px;padding:18px"><h3 style="margin:0 0 10px">วิธีเล่น (สั้น ๆ)</h3><div style="opacity:.92;line-height:1.45">'+msg+'</div><button id="ok" style="margin-top:14px;background:#1e293b;border:1px solid #334155;color:#fff;border-radius:10px;padding:8px 14px;cursor:pointer">เริ่มเลย</button></div>';
    document.body.appendChild(d); const bye=()=>{localStorage.setItem(key,'1'); d.remove();}; d.querySelector('#ok').onclick=bye; d.addEventListener('click',e=>{if(e.target===d) bye();}); }
  function candidatePaths(file){ return ['../assets/backgrounds/'+file,'./assets/backgrounds/'+file,'/webxr-health-mobile/fitness-duo/assets/backgrounds/'+file,'/fitness-duo/assets/backgrounds/'+file]; }
  function probeImg(u){return new Promise((res,rej)=>{const i=new Image(); i.onload=()=>res(u); i.onerror=()=>rej(u); i.src=u+'?v='+Date.now();});}
  async function findFirstOK(file){ for(const u of candidatePaths(file)){ try{ await probeImg(u); return u;}catch(e){} } throw new Error('bg not found'); }
  async function swapSky(theme){ const file=theme==='space'?'space_sky.jpg':theme==='jungle'?'jungle_sky.jpg':'city_sky.jpg'; const id='bg-'+theme;
    try{ const scene=document.querySelector('a-scene'); if(scene && !scene.hasLoaded) await new Promise(r=>scene.addEventListener('loaded',r,{once:true}));
      const url=await findFirstOK(file); let assets=document.querySelector('a-assets'); if(!assets){ assets=document.createElement('a-assets'); document.querySelector('a-scene').appendChild(assets); }
      const img=document.createElement('img'); img.id=id; img.src=url+'?v='+Date.now(); assets.appendChild(img); skyEl.setAttribute('src','#'+id); statusEl.textContent='Sky OK • '+theme; }catch(e){ skyEl.removeAttribute('src'); statusEl.textContent='Sky Fallback • '+theme; } }
  function laneX(i){ return [-0.9,0,0.9][i]; }
  let THEME='city', running=false,raf=0,t0=0,elapsed=0,score=0,combo=0,best=0,fever=false,feverEnd=0,tutorial=true,tutEndAt=10;
  let calibMs=parseInt(localStorage.getItem('fd_rhythm_offset_ms')||'0',10);
  const notes=[]; const duration=60; const bpm=108; const beatSec=60/bpm; const START_OFFSET=1.6; const HIT_P=0.055, HIT_G=0.11; let nextNoteIdx=0, flatNotes=[];
  let actx=null, master=null; function ensureAudio(){ if(actx) return; const AC=window.AudioContext||window.webkitAudioContext; if(!AC) return; actx=new AC(); master=actx.createGain(); master.gain.value=0.18; master.connect(actx.destination); }
  function tick(f=880,d=0.05,g=0.18){ if(!actx) return; const o=actx.createOscillator(), v=actx.createGain(); o.type='square'; o.frequency.value=f; o.connect(v); v.connect(master); const t=actx.currentTime; v.gain.setValueAtTime(0,t); v.gain.linearRampToValueAtTime(g,t+0.005); v.gain.exponentialRampToValueAtTime(0.0001,t+d); o.start(t); o.stop(t+d+0.02); }
  ['pointerdown','touchend','keydown','click'].forEach(ev=>window.addEventListener(ev,()=>{ ensureAudio(); window.__audioUnlocked=true; },{once:true,capture:true}));
  function laneColors(){ if(THEME==='space') return ['#7c3aed','#334155','#06b6d4']; if(THEME==='jungle') return ['#14532d','#334155','#166534']; return ['#0ea5e9','#334155','#22c55e']; }
  function buildLaneUI(){ [...root.children].forEach(k=>k.remove()); const lanes=laneColors();
    [-0.9,0,0.9].forEach((x,i)=>{const bg=document.createElement('a-entity'); bg.setAttribute('geometry','primitive:plane; width:0.98; height:1.35'); bg.setAttribute('material','color:'+lanes[i]+'; opacity:0.18; shader:flat'); bg.setAttribute('position',x+' 0 0.02'); root.appendChild(bg);
      const tag=document.createElement('a-entity'); tag.setAttribute('text','value:'+['L(A/←)','C(S/↑)','R(D/→)'][i]+'; width:2.2; align:center; color:#9fb1d1'); tag.setAttribute('position',x+' -0.75 0.05'); root.appendChild(tag);
      const pad=document.createElement('a-entity'); pad.setAttribute('geometry','primitive:plane; width:0.95; height:0.55'); pad.setAttribute('material','color:#0f172a; opacity:0.95; shader:flat'); pad.setAttribute('position',x+' -0.55 0.06');
      const t=document.createElement('a-entity'); t.setAttribute('text','value:'+['L','C','R'][i]+'; width:3; align:center; color:#93c5fd'); t.setAttribute('position','0 0 0.01'); pad.appendChild(t); pad.addEventListener('click',()=>judge(i)); root.appendChild(pad); });
    const hit=document.createElement('a-entity'); hit.setAttribute('geometry','primitive:ring; radiusInner:0.07; radiusOuter:0.09; segmentsTheta:64'); hit.setAttribute('material','color:#93c5fd; opacity:0.95; shader:flat'); hit.setAttribute('position','0 0 0.06'); hit.setAttribute('animation__pulse','property: scale; to:1.07 1.07 1; dir:alternate; dur:480; loop:true'); root.appendChild(hit); }
  function setHUD(msg){ const f=fever?' • FEVER!':' '; hud.setAttribute('text','value:['+THEME.toUpperCase()+'] Score '+score+' • Combo '+combo+' (Best '+best+')'+f+'\nให้โน้ตถึงวงฟ้าแล้วกดเลนให้ตรง (A/S/D หรือ L/C/R)\n'+(msg||'')+'; width:5.9; align:center; color:#e2e8f0'); }
  function toast(txt,color='#93c5fd',y=1.05,ms=520){ const e=document.createElement('a-entity'); e.setAttribute('text','value:'+txt+'; width:5; align:center; color:'+color); e.setAttribute('position','0 '+y+' 0.05'); root.appendChild(e); e.setAttribute('animation__up','property: position; to: 0 1.25 0.05; dur:360; easing:easeOutQuad'); setTimeout(()=>e.remove(),ms); }
  function buildFlatNotes(){ const arr=[]; let t=START_OFFSET+0.8; for(let i=0;i<8;i++){ const lane=i%3; arr.push({lane,t:t+i*beatSec*0.9,dodge:false}); } t+=8*beatSec*0.9; for(let i=0;i<32;i++){ const lane=(Math.random()*3|0); const isDodge=Math.random()<0.2; arr.push({lane,t:t+i*beatSec*0.8,dodge:isDodge}); } flatNotes=arr.sort((a,b)=>a.t-b.t); nextNoteIdx=0; }
  function spawn(it){ let geom,mat; if(it.dodge){ geom='ring; radiusInner:0.06; radiusOuter:0.18'; mat='color:#ef4444; shader:flat; opacity:0.98'; } else { geom='circle; radius:0.16'; mat='color:hsl(200,70%,70%); shader:flat; opacity:0.98'; } const n=document.createElement('a-entity'); n.classList.add('note'); n.setAttribute('geometry','primitive:'+geom); n.setAttribute('material',mat); n.object3D.position.set(laneX(it.lane),0,3.0); root.appendChild(n); notes.push({el:n,lane:it.lane,t:it.t,judged:false,dodge:it.dodge}); }
  function judge(lane){ ensureAudio(); let best=null,bestErr=9; const target=elapsed + (calibMs/1000); for(const it of notes){ if(it.judged||it.lane!==lane) continue; const err=Math.abs(it.t - target); if(err<bestErr){ best=it; bestErr=err; } }
    if(!best){ combo=0; toast('Miss','#fecaca'); return; } if(best.dodge && bestErr<=0.11){ combo=0; toast('Dodge Fail','#fecaca'); tick(300,0.05,0.18); best.judged=true; best.el.setAttribute('visible','false'); return; }
    if(bestErr>0.11){ combo=0; toast('Miss','#fecaca'); return; } best.judged=true; best.el.setAttribute('visible','false'); const perfect=bestErr<=0.055; score+=perfect?300:160; combo++; best=Math.max(best,combo); tick(perfect?1000:820,0.05,perfect?0.2:0.16); toast(perfect?'Perfect +300':'Good +160', perfect?'#7dfcc6':'#a7f3d0'); if(!fever && combo>0 && combo%8===0){ fever=true; feverEnd=elapsed+6; toast('FEVER! ✨','#7dfcc6'); } }
  function loop(){ if(!running) return; if(paused){ raf=requestAnimationFrame(loop); return; } const now=performance.now()/1000; elapsed=(now - t0) - pauseAccum;
    const lead=tutorial?1.8:1.2; while(nextNoteIdx<flatNotes.length && flatNotes[nextNoteIdx].t <= elapsed + lead){ spawn(flatNotes[nextNoteIdx]); nextNoteIdx++; }
    const speedZ=(tutorial?1.4:1.65) + (fever?0.12:0); for(const it of notes){ if(it.judged) continue; const dtz=it.t - elapsed; it.el.object3D.position.z=Math.max(0, dtz*speedZ); if(dtz < -0.22 && !it.judged){ if(it.dodge){ score+=80; toast('Dodge OK +80','#93c5fd',1.0,420);} else { combo=0; toast('Miss','#fecaca'); } it.judged=true; it.el.setAttribute('visible','false'); } }
    if(fever && elapsed>=feverEnd) fever=false; if(tutorial && elapsed>=10){ tutorial=false; } if(elapsed>=60) return end('Stage Clear'); setHUD(); raf=requestAnimationFrame(loop); }
  function start(){ const t=(window.__OVERRIDE_THEME||'city').toLowerCase(); THEME=t; swapSky(THEME); running=true; t0=performance.now()/1000; elapsed=0; pauseAccum=0; paused=false; score=0; combo=0; best=0; fever=false; feverEnd=0; notes.splice(0).forEach(n=>n.el?.remove()); buildLaneUI(); buildFlatNotes(); setHUD('Tutorial: ดูจังหวะช้า ๆ ก่อน'); tick(660,0.05,0.18); raf=requestAnimationFrame(loop); }
  function end(msg){ running=false; cancelAnimationFrame(raf); setHUD(msg+' • Score '+score); }
  function reset(){ running=false; cancelAnimationFrame(raf); notes.splice(0).forEach(n=>n.el?.remove()); [...root.children].forEach(k=>k.remove()); setTimeout(()=>{ buildLaneUI(); setHUD('พร้อมเริ่ม'); },0); pauseAccum=0; paused=false; }
  function bind(){ btnStart.onclick=()=>{ ensureAudio(); if(!running) start(); }; btnReset.onclick=()=>reset(); btnPause.onclick=()=>pauseGame(); btnResume.onclick=()=>resumeGame();
    window.addEventListener('keydown',e=>{ const k=e.key.toLowerCase(); if(k==='a'||k==='arrowleft') judge(0); if(k==='s'||k==='arrowup') judge(1); if(k==='d'||k==='arrowright') judge(2); if(k===' '||k==='enter'){ if(!running) btnStart.click(); } if(k==='p'){ paused?resumeGame():pauseGame(); } });
    showFirstTimeOverlay('fd_seen_tutorial_rhy','รอให้โน้ตถึงวงฟ้า แล้วกดเลนที่ตรง (A/S/D หรือแตะ L/C/R)<br>✔️ ตรงเป๊ะ = Perfect • ใกล้เคียง = Good • พลาด = Miss<br>Tip: คอมโบ 8 ครั้งจะเข้า Fever ชั่วคราว');
    statusEl && (statusEl.textContent='พร้อมเริ่ม • เลือกธีมแล้วกด Start'); }
  const scene=document.querySelector('a-scene'); if(!scene.hasLoaded){ scene.addEventListener('loaded', bind, {once:true}); } else bind();
})();