(()=>{const W={
6:{t:'การยอมรับและการติดตามย้อนกลับ',a:'Requirements Pack',q:'เกณฑ์ใดตรวจสอบได้ที่สุด',o:['ระบบใช้งานง่าย','เมื่อส่งคำขอสำเร็จ ระบบบันทึกเลขอ้างอิงและแสดงภายใน 2 วินาที','ผู้ใช้พึงพอใจ'],c:1},
7:{t:'สถาปัตยกรรมและขอบเขต AI',a:'Context/Component Design',q:'เมื่อโมเดลไม่มั่นใจ ควรออกแบบอย่างไร',o:['แสดงผลทันทีโดยไม่บอกข้อจำกัด','ส่งต่อ human review ตาม threshold พร้อมบันทึกเหตุผล','ลบผลลัพธ์ทิ้งโดยไม่มี log'],c:1},
8:{t:'ข้อตกลงส่วนเชื่อมต่อและเส้นทางล้มเหลว',a:'Architecture Evidence Pack',q:'ข้อใดเป็น invariant ที่เหมาะสม',o:['ทุกคำตอบต้องถูกเสมอ','คำขอที่ยืนยันแล้วต้องมีสถานะเดียวใน source of truth','ระบบต้องเร็วที่สุด'],c:1},
9:{t:'การทวนสอบและการตรวจสอบความตรงตามการใช้งาน',a:'Testing Matrix',q:'test oracle ควรอ้างอิงสิ่งใด',o:['ความรู้สึกของผู้พัฒนา','acceptance criteria ที่ติดตามกลับไปยัง requirement','จำนวนบรรทัดโค้ด'],c:1},
10:{t:'AI testing และ regression',a:'Evidence-based Debugging Pack',q:'ก่อนปล่อยโมเดลใหม่ควรทำสิ่งใด',o:['เปลี่ยน production ทันที','รันชุด regression และ failure injection เทียบ baseline','ลบผลทดสอบเดิม'],c:1},
11:{t:'Evolution และผลกระทบของการเปลี่ยนแปลง',a:'Impact Map',q:'เมื่อเปลี่ยน model version ต้องตรวจอะไร',o:['เฉพาะชื่อไฟล์','ผลกระทบต่อ data contract, test, monitoring และ rollback','เฉพาะสีของ UI'],c:1},
12:{t:'Migration, release และ recovery',a:'Change-to-Release Pack',q:'แผน rollout ที่ปลอดภัยควรมีอะไร',o:['deploy ครั้งเดียวโดยไม่มีทางย้อนกลับ','compatibility check, monitoring threshold และ rollback owner','ประกาศหลังเกิด incident'],c:1},
13:{t:'Project, cost และ risk',a:'AI Project Planning Studio',q:'การประมาณงานที่มีความไม่แน่นอนควรเริ่มอย่างไร',o:['ใช้ตัวเลขเดียวโดยไม่ระบุสมมติฐาน','ทำ WBS และ three-point estimate พร้อม risk register','ตัดงานทดสอบออก'],c:1},
14:{t:'Responsible AI assurance',a:'Responsible AI Assurance Sheet',q:'human oversight ที่มีความหมายต้องมีอะไร',o:['มีชื่อผู้รับผิดชอบอย่างเดียว','มีข้อมูล อำนาจ เวลา และความสามารถในการแทรกแซง','ให้มนุษย์ดูย้อนหลังเมื่อจบโครงการ'],c:1},
15:{t:'Release readiness และการสังเคราะห์',a:'Final AI Software Engineering Dossier',q:'การตัดสินใจ release ที่มีหลักฐานควรระบุอะไร',o:['Go เสมอเมื่อโมเดลแม่น','Go/Pilot/No-Go พร้อม evidence, limitation และ residual risk','เฉพาะวัน deploy'],c:1}
};const m=location.pathname.match(/w(\d+)\.html$/i);if(!m||!W[m[1]])return;const n=+m[1],d=W[n],K='csai2401-progress-v2',s=JSON.parse(localStorage.getItem(K)||'{}'),p=s.progress||{};const need=n===10?[6,7,8,9]:n===15?[10,11,12,13,14]:[];const blocked=need.some(x=>!p[x]);const id=s.challenge&&s.challenge.week===n?s.challenge:{week:n,id:crypto.randomUUID(),used:false};s.challenge=id;localStorage.setItem(K,JSON.stringify(s));const b=document.createElement('main');b.lang='th';b.style.cssText='max-width:720px;margin:16px auto;padding:20px;border-radius:16px;background:#102a43;color:#f0f6fc;font-family:system-ui;box-shadow:0 8px 24px #0003';b.innerHTML='<div style="font-size:13px;opacity:.8">CSAI2401 · สัปดาห์ที่ '+n+'/15 '+([10,15].includes(n)?'· BOSS GATE':'')+'</div><h1 style="font-size:24px">'+d.t+'</h1><p><b>ชิ้นงาน:</b> '+d.a+'</p>'+ (blocked?'<p style="color:#ffd166">ด่านนี้ล็อกอยู่: ต้องผ่านสัปดาห์ '+need.join(', ')+' ก่อน</p>':'<p>'+d.q+'</p><div id="opts">'+d.o.map((x,i)=>'<label style="display:block;padding:12px;margin:8px 0;border:1px solid #486581;border-radius:10px"><input type="radio" name="answer" value="'+i+'"> '+x+'</label>').join('')+'</div><input id="evidence" required placeholder="อ้างอิง evidence อย่างน้อย 1 รายการ" style="width:100%;box-sizing:border-box;padding:12px;border-radius:8px;border:0;margin:8px 0"><button id="submit" style="padding:12px 16px;border:0;border-radius:10px;background:#ffd166;color:#102a43;font-weight:700">ส่งคำตอบ</button><p id="feedback"></p>')+'<small id="status"></small>';document.body.prepend(b);const st=b.querySelector('#status');st.textContent='ผ่านแล้ว '+Object.keys(p).filter(k=>p[k]&&p[k].score===1).length+'/10 ด่าน';if(blocked)return;const f=b.querySelector('#feedback');b.querySelector('#submit').onclick=()=>{const cur=JSON.parse(localStorage.getItem(K)||'{}');if(!cur.challenge||cur.challenge.id!==id.id||cur.challenge.used){f.textContent='คำตอบนี้ถูกใช้แล้ว กรุณาเริ่ม challenge ใหม่';return}const ans=b.querySelector('input[name=answer]:checked'),ev=b.querySelector('#evidence').value.trim();if(!ans||!ev){f.textContent='เลือกคำตอบและระบุ evidence ก่อนส่ง';return}cur.challenge.used=true;cur.progress=cur.progress||{};const ok=+ans.value===d.c;cur.progress[n]=ok?{score:1,artifact:d.a,evidence:ev}: {score:0,artifact:d.a,evidence:ev};localStorage.setItem(K,JSON.stringify(cur));f.style.color=ok?'#8ff0a4':'#ffb4a2';f.textContent=ok?'ผ่าน: บันทึก '+d.a+' และ evidence แล้ว':'ยังไม่ผ่าน: ทบทวนเกณฑ์และส่ง challenge ใหม่';st.textContent='ผ่านแล้ว '+Object.keys(cur.progress).filter(k=>cur.progress[k].score).length+'/10 ด่าน';if(!ok){cur.challenge={week:n,id:crypto.randomUUID(),used:false};localStorage.setItem(K,JSON.stringify(cur))}}})()